[versions]
android-gradle-plugin = "8.3.1"
apollo = "3.8.3"
appcompat = "1.7.0-alpha03"
checker-qual = "3.42.0"
coil = "2.6.0"
constraintlayout = "2.1.4"
core = "1.12.0"
coroutines = "1.8.0"
draglistview = "1.7.3"
fetch = "3.1.6"
flexbox = "3.0.0"
fragment = "1.6.2"
glide = "4.16.0"
glide-webpdecoder = "2.6.4.16.0"
gson = "2.10.1"
hilt = "2.51.1"
hilt-extension-compiler = "1.2.0"
hilt-work = "1.2.0"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"
lifecycle = "2.7.0"
material = "1.11.0"
media3 = "1.3.0"
navigation = "2.7.7"
okhttp = "5.0.0-alpha.12"
okio = "3.9.0"
open-m3u8 = "0.2.6"
paging = "3.2.1"
preference = "1.2.1"
retrofit = "2.11.0"
room = "2.6.1"
swiperefreshlayout = "1.1.0"
webkit = "1.10.0"
work = "2.9.0"

[libraries]
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checker-qual" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
draglistview = { module = "com.github.woxthebox:draglistview", version.ref = "draglistview" }
fetch = { module = "androidx.tonyodev.fetch2:xfetch2", version.ref = "fetch" }
fetch-okhttp = { module = "androidx.tonyodev.fetch2okhttp:xfetch2okhttp", version.ref = "fetch" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-webpdecoder = { module = "com.github.zjupure:webpdecoder", version.ref = "glide-webpdecoder" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-extension-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-extension-compiler" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
open-m3u8 = { module = "com.iheartradio.m3u8:open-m3u8", version.ref = "open-m3u8" }
paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
apollo3 = { id = "com.apollographql.apollo3", version.ref = "apollo" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }

