name: Android CI

on:
  push:
    branches: [ api_16 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk

    - name: Update git tag
      run: |
        git tag -f api16
        git push -f origin api16

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: app/build/outputs/apk/release/*.apk
        generateReleaseNotes: true
        makeLatest: false
        tag: "api16"
