name: Android CI

on:
  push:
    branches: [ fdroid ]

jobs:
  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "00_fdroid"
          prerelease: false
          title: "f-droid"
